import type { Metadata } from "next";
import "./globals.css";

// <a href="https://www.freepik.es/vector-gratis/plantilla-vector-tarjeta-ano-nuevo-blue-mt-fuji-decorado-patrones-japoneses-antiguos_32166524.htm#query=mount%20fuji,%20japan&position=2&from_view=search&track=ais&uuid=6102c5d6-edc5-44ed-89d6-7d27b4c79468">Imagen de callmetak</a> en Freepik

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
